# load packages 
library(scater)
library(scran)
library(bluster)
library(cluster)
library(igraph)
library(pheatmap)
library(patchwork)
library(tidyverse)

# load data 
sce <- readRDS("R_objects/Caron_batch_corrected.500.rds")

# check samples 
table(sce$SampleName)

## -- Exercise 1 -- ############################################################

# For this exercise please run the clustering using the "leiden" method.

# Set the *k* to *20* and add the results of the clustering to the `sce` object
# in a new column called "leiden20".

# How many clusters does this result in?
  
# Visualize the clusters by plotting the t-SNE with the cells coloured according
# to your new clustering.

################################################################################



## -- Exercise 2 -- ############################################################

# For this exercise, run `clusterSweep`with additional parameters. This time:
# * test the walktrap, louvain and leiden methods
# * test *k* set to 10, 15, 20 and 25

# This will test 12 different clusterings.

YOUR CODE HERE 

# Now plot the number of clusters generated by each clustering and the mean
# silhouette width. You will need to adjust the plotting parameters to plot a
# different coloured line for each clustering algorithm (walktap, louvain and
# leiden).

YOUR CODE HERE 

# BONUS EXERCISE: if you have time, select 1 or 2 of the clusterings, calculate
# the silhouette widths and examine them further using the beeswarm plot and the
# silhouette grid.
# We have provided the two functions for generating these plots below

# silhouette width beeswarm 
plotSilBeeswarm <- function(silDat){
  silTab <- silDat %>% 
    as.data.frame() %>% 
    mutate(closestCluster = ifelse(width > 0, cluster, other) %>% factor())
  
  plt <- silTab %>% 
      ggplot(aes(x=cluster, y=width, colour=closestCluster)) +
        ggbeeswarm::geom_quasirandom(method="smiley", alpha=0.6) +
        theme_bw()
  
  plt <- scater:::.resolve_plot_colours(plt, silTab$closestCluster, "closestCluster")
  plt
}

# silhouette width grid 
plotSilGrid <- function(silDat){
  silDat %>% 
    as.data.frame() %>% 
    mutate(closestCluster = ifelse(width > 0, cluster, other) %>% factor()) %>% 
    count(cluster, closestCluster,  name="olap") %>% 
    group_by(cluster) %>% 
    mutate(total  = sum(olap)) %>% 
    mutate(proportion = olap / total) %>% 
    mutate(proportion = ifelse(cluster == closestCluster, proportion, -proportion)) %>% 
    ggplot(aes(x = cluster, y = closestCluster)) +
      geom_tile(aes(fill = proportion)) +
      geom_text(aes(label = olap), size=5) +
      scale_fill_gradientn(colors = c("#fc8d59", "#ffffbf", "#91cf60"),
                            limits = c(-1, 1)) +
      geom_vline(xintercept=seq(0.5, 30.5, by=1)) +
      geom_hline(yintercept=seq(0.5, 30.5, by=1), colour="lightgrey", linetype=2) +
      guides(fill = "none") +
      theme(
          aspect.ratio = 1,
          panel.background = element_blank())
}


################################################################################
