---
title: "Introduction to single-cell RNA-seq analysis"
subtitle: 'Multi-sample comparisons - Exercise 1'
author: "Abbi Edwards, Stephane Ballereau"
output:
  html_document:
    df_print: paged
    toc: yes
    number_sections: true
    code_folding: hide
  html_notebook:
    code_folding: hide
    toc: yes
    toc_float: yes
    number_sections: true
---


```{r, message=FALSE, warning=FALSE}
library(scater)
library(scran)
library(batchelor)
library(edgeR)
library(tidyverse)
library(patchwork)
library(DT)
fontsize <- theme(axis.text=element_text(size=12), axis.title=element_text(size=16))
```

Source: [Multi-sample comparisons](https://osca.bioconductor.org/multi-sample-comparisons.html) of the OSCA book.

## Exercise 1 - differential expression

Identify label-specific DE genes that are significant in cluster 4 yet not DE in any other label.

Plot the top-ranked gene for inspection.

```{r}
# load RObjects until this point

load("../Robjects/10_exercise1.RData")

```


```{r}
# get c10's 'unique.degs':






```

```{r}
# Choosing the top-ranked gene for inspection:





# plot expression of top gene
# use plotExpression()

```

